### ISSUE TITLE
[BUG]helm install kubechat failed 

### ISSUE THREAD

**Issue by ahjing99** [apecloud/ApeRAG#393]
```
➜  ~ helm uninstall kubechat -n kubechat
release "kubechat" uninstalled

➜  ~ helm repo update kubeblocks
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "kubeblocks" chart repository
Update Complete. ⎈Happy Helming!⎈
➜  ~ helm upgrade -i kubechat kubeblocks/kubechat --namespace kubechat -f values.yaml --version v0.1.4-alpha.6
Release "kubechat" does not exist. Installing it now.
coalesce.go:220: warning: cannot overwrite table with non table for kubechat.django.modelServers (map[])
Error: Deployment.apps "django" is invalid: [spec.template.spec.affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution[0].podAffinityTerm.topologyKey: Required value: can not be empty, spec.template.spec.affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution[0].podAffinityTerm.topologyKey: Invalid value: "": name part must be non-empty, spec.template.spec.affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution[0].podAffinityTerm.topologyKey: Invalid value: "": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')]
```

values.yaml
```
➜  ~ cat values.yaml
image:
  registry: docker.io
  tag: "v0.1.4-alpha.6"
  pullPolicy: "Always"

django:
  dataPath: /mnt/stateful_partition
  modelServers:
    - name: "chatglm-pro"
      label: "ChatGLM Pro"
      enabled: "true"
    - name: "chatglm-std"
      label: "ChatGLM Std"
      enabled: "true"
    - name: "chatglm-lite"
      label: "ChatGLM Lite"
      enabled: "true"
    - name: "chatgpt-3.5"
      label: "ChatGPT 3.5"
      enabled: "true"
    - name: "chatgpt-4"
      label: "ChatGPT 4"
      enabled: "true"
    - name: "azure-openai"
      label: "Azure OpenAI"
      enabled: "true"
    - name: "baichuan-53b"
      label: "BaiChuan 53b"
      enabled: "true"
    - name: "ernie-bot-turbo"
      label: "WenXinYiYan"
      enabled: "true"
    - name: "baichuan-13b"
      label: "BaiChuan 13b"
      endpoint: "http://baichuan-13b-vllm:8000"
      enabled: "true"
    - name: "vicuna-13b"
      label: "Vicuna 13b"
      endpoint: "http://vicuna-13b-vllm:8000"
      enabled: "true"
    - name: "chatglm2-6b"
      label: "ChatGLM2 6b"
      endpoint: "http://llmserver-chatglm2-6b:8000"
      enabled: "false"
    - name: "guanaco-33b"
      label: "Guanaco 33b"
      endpoint: "http://llmserver-guanaco-33b:8000"
      enabled: "false"
    - name: "falcon-40b"
      label: "Falcon 40b"
      endpoint: "http://llmserver-falcon-40b:8000"
      enabled: "false"
    - name: "gorilla-7b"
      label: "Gorilla 7b"
      endpoint: "http://llmserver-gurilla-7b:8000"
      enabled: "false"
```
